config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :profile, only: [:show, :update]
  resources :repositories
  root 'home#index'
end

app/models/repository.rb
class Repository
  API = Github.repos
  def initialize(user)
    @user = user.github_username
  end

  def count
    API.list(user: @user).count
  end

  def fetch(per_page: 10, page: 1)
    API.list(user: @user, per_page: per_page, page: page)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates_presence_of :github_username, on: :update
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/github_base_controller.rb
class GithubBaseController < ApplicationController
  before_action :check_github_account

  private
  def check_github_account
    redirect_to profile_path, flash: { error: 'Please input your github username' } and return if current_user.github_username.blank?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to :back, notice: "Successfully updated profile"
    else
      render 'show'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :github_username)
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < GithubBaseController
  def index
    page = params[:page] || 1
    per_page = params[:per_page] || 10
    repository = Repository.new(current_user)
    @repositories = repository.fetch(page: page, per_page: per_page)
    @repositories_paginator = Kaminari.paginate_array(@repositories, total_count: repository.count).page(page).per(per_page)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
.well
  Well, I guess, one day, something useful will be here =)).
  In the meantime feel free to browse repositories.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Github API on Rails
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tag
  %body
    = render 'shared/navigation'
    .container
      = flash_messages(:close, :fade)
      = yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %title Github API on Rails
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tag
  %body
    .container.devise
      .col-sm-6.col-sm-offset-3
        = yield

app/views/profiles/show.html.haml
%h2 Your profile
= simple_form_for @user, url: profile_path do |f|
  = f.input :email
  = f.input :github_username
  = f.button :submit, 'Save'

app/views/repositories/index.html.haml
= paginate @repositories_paginator
%table.table
  %tbody
    - @repositories.each do |repo|
      %tr
        %td= repo.name
        %td= repo.owner.login

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  / brand and toggle get grouped for better mobile display
  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-ex1-collapse", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand{href: "#"} Github API
  .collapse.navbar-collapse.navbar-ex1-collapse
    %ul.nav.navbar-nav
      %li
        = link_to 'My Repositories', repositories_path
    %ul.nav.navbar-nav.navbar-right
      %li.dropdown
        %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
          = current_user.email
          %b.caret
        %ul.dropdown-menu
          %li
            = link_to 'Profile', profile_path
          %li
            = link_to 'Log Out', destroy_user_session_path, method: :delete